### ISSUE TITLE
Error: convert.im6

### ISSUE THREAD

**Issue by alejonext** [eivindfjeldstad/imagemagick-stream#13]
Well...whats is this?
```console
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: convert.im6: Too many IDAT's found `/tmp/magick-U-0S9kiM' @ error/png.c/MagickPNGErrorHandler/1728
    at ReaDuplexer.ImageMagick.onerror (/home/pol/Work/node_modules/imagemagick-stream/index.js:241:30)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:526:21)
```

**Comment by eivindfjeldstad** [comment]
You need to attach an error handler, just like you would any other stream
