### ISSUE TITLE
errnoException

### ISSUE THREAD

**Issue by alejonext** [eivindfjeldstad/imagemagick-stream#14]
Well, I think it is a bug in nodejs
```console
child_process.js:935
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
  at errnoException (child_process.js:988:11)
  at ChildProcess.spawn (child_process.js:935:11)
  at exports.spawn (child_process.js:723:9)
  at ImageMagick.spawn (/.........../node_modules/imagemagick-stream/index.js:230:14)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by eivindfjeldstad** [comment]
It means you have too many open files. You should probably raise the ulimit on your OS

**Comment by alejonext** [comment]
Ok! I knew it was not a bug! :)
