### ISSUE TITLE
 code=ENOENT, errno=ENOENT, syscall=spawn convert, path=convert, spawnargs=[-, -resize, 40x40, -]

### ISSUE THREAD

**Issue by testtshoretel** [eivindfjeldstad/imagemagick-stream#24]
@eivindfjeldstad    

I download file from S3 and try to resize and got this error: 

 code=ENOENT, errno=ENOENT, syscall=spawn convert, path=convert, spawnargs=[-, -resize, 40x40, -]
 2016-11-16T22:03:20.958Z - error: uncaughtException: dest.end is not a function 

Here is my code: 
 var read = Streamifier.createReadStream(result.Body);
            var resize = im().resize(self.width.toString() + 'x' + self.height.toString());
            var write = new stream();
            write.writable = true;
            read.pipe(resize).pipe(write);

Do you know what is wrong here?

**Comment by eivindfjeldstad** [comment]
Can you post the full stack trace?

**Comment by testtshoretel** [comment]
@eivindfjeldstad  Here you go, thanks for the quick response.
2016-11-16T22:03:20.964Z - error: uncaughtException: dest.end is not a function date=Wed Nov 16 2016 17:03:20 GMT-0500 (EST), pid=24625, uid=0, gid=0, cwd=/usr/share/media_server, execPath=/usr/bin/node, version=v6.7.0, argv=[/usr/bin/node, /usr/share/media_server/server.js], rss=43487232, heapTotal=37785600, heapUsed=21953904, loadavg=[0.03857421875, 0.02685546875, 0.04638671875], uptime=2350581, trace=[column=10, file=/usr/share/media_server/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js, function=ImageMagick.onend, line=504, method=onend, native=false, column=16, file=events.js, function=ImageMagick.g, line=291, method=g, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false, column=7, file=events.js, function=ImageMagick.emit, line=185, method=emit, native=false, column=12, file=/usr/share/media_server/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js, function=endReadableNT, line=926, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=122, method=_tickDomainCallback, native=false], stack=[TypeError: dest.end is not a function,     at ImageMagick.onend (/usr/share/media_server/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:504:10),     at ImageMagick.g (events.js:291:16),     at emitNone (events.js:91:20),     at ImageMagick.emit (events.js:185:7),     at endReadableNT (/usr/share/media_server/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:926:12),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickDomainCallback (internal/process/next_tick.js:122:9)]
2016-11-16T22:03:20.965Z - error:

**Comment by testtshoretel** [comment]
@eivindfjeldstad 

A new stack.

2016-11-17T01:22:59.630Z - error: uncaughtException: spawn convert ENOENT date=Wed Nov 16 2016 20:22:59 GMT-0500 (EST), pid=25260, uid=0, gid=0, cwd=/usr/share/media_server, execPath=/usr/bin/node, version=v6.7.0, argv=[/usr/bin/node, /usr/share/media_server/server.js], rss=43925504, heapTotal=36737024, heapUsed=20802784, loadavg=[0.005859375, 0.02587890625, 0.04541015625], uptime=2362559, trace=[column=11, file=util.js, function=exports._errnoException, line=1036, method=_errnoException, native=false, column=32, file=internal/child_process.js, function=Process.ChildProcess._handle.onexit, line=193, method=ChildProcess._handle.onexit, native=false, column=16, file=internal/child_process.js, function=onErrorNT, line=359, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=122, method=_tickDomainCallback, native=false], stack=[Error: spawn convert ENOENT,     at exports._errnoException (util.js:1036:11),     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32),     at onErrorNT (internal/child_process.js:359:16),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickDomainCallback (internal/process/next_tick.js:122:9)]
2016-11-17T01:22:59.630Z - error:  code=ENOENT, errno=ENOENT, syscall=spawn convert, path=convert, spawnargs=[-, -resize, 40x40, -]

**Comment by eivindfjeldstad** [comment]
Hmm, I don't think the problem is in this repo. My guess is it has something to do with that Streamifier line, but I don't have time to investigate. If you can provide a failing test case I'll be happy to help, but without that there's really not much I can do.
